### ISSUE TITLE
torch.backends.cudnn.CuDNNError: 8: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by ruyiluo** [danieljf24/dual_encoding#14]
Thanks your good job, but
When I run `./do_all.sh msrvtt10ktrain msrvtt10kval msrvtt10ktest full` got this error.

**Comment by danieljf24** [comment]
I guess it's the problem with your cuda or cudnn.

**Comment by ruyiluo** [comment]
Yeah, it works now! Thanks.

**Comment by yuzhiw** [comment]
Excuse me,My cuda version is cuda10.0，because my graphics card is nvidia RTX 2080Ti，this nvidia is not supported by cuda 9.0 ,could i use cuda10.0 to run the demo code?
